/* eslint-disable */
/**
 * Generated by convex codegen.
 * This file is auto-replaced when `npx convex dev` runs.
 */
import { anyApi } from "convex/server";

export const api = anyApi;
export const internal = anyApi;
