/* eslint-disable */
/**
 * Generated by convex codegen.
 * This file is auto-replaced when `npx convex dev` runs.
 */
export {
  query,
  mutation,
  action,
  internalQuery,
  internalMutation,
  internalAction,
  httpAction,
} from "convex/server";
